/**
 * Canonical enumerations for Dayliff 1000 Eyes
 * Requirements: all
 */

/** Lifecycle stages a Service_Request passes through */
export enum JourneyStage {
  Inquiry = 'Inquiry',
  SalesReview = 'Sales Review',
  EngineeringDesign = 'Engineering Design',
  Quotation = 'Quotation',
  Approval = 'Approval',
  Dispatch = 'Dispatch',
  Delivery = 'Delivery',
  Completed = 'Completed',
  Cancelled = 'Cancelled',
}

/** Terminal stages — no SLA evaluation applies */
export const TERMINAL_STAGES = [JourneyStage.Completed, JourneyStage.Cancelled] as const;

/** Roles defined in the RBAC permission matrix */
export enum UserRole {
  Administrator = 'Administrator',
  RegionalManager = 'Regional Manager',
  SalesEngineer = 'Sales Engineer',
  BackendDesigner = 'Backend Designer',
  LogisticsOfficer = 'Logistics Officer',
}

/** Alert severity levels */
export enum AlertSeverity {
  Info = 'Info',
  Warning = 'Warning',
  Critical = 'Critical',
}

/** Alert lifecycle state machine: Created → Acknowledged → Resolved → Archived */
export enum AlertLifecycleState {
  Created = 'Created',
  Acknowledged = 'Acknowledged',
  Resolved = 'Resolved',
  Archived = 'Archived',
}

/** Allowed lifecycle transitions */
export const ALERT_LIFECYCLE_TRANSITIONS: Record<AlertLifecycleState, AlertLifecycleState | null> =
  {
    [AlertLifecycleState.Created]: AlertLifecycleState.Acknowledged,
    [AlertLifecycleState.Acknowledged]: AlertLifecycleState.Resolved,
    [AlertLifecycleState.Resolved]: AlertLifecycleState.Archived,
    [AlertLifecycleState.Archived]: null,
  };

/** Alert types generated by the platform */
export enum AlertType {
  Operational = 'Operational Alert',
  SLABreach = 'SLA Breach Alert',
  CriticalDelay = 'Critical Delay Alert',
  Escalation = 'Escalation Alert',
}

/** Source systems that can emit events */
export enum SourceSystem {
  CRM = 'CRM',
  ERP = 'ERP',
  EngineeringSoftware = 'Engineering Software',
  QuotationSystem = 'Quotation System',
  LogisticsPlatform = 'Logistics Platform',
  Manual = 'Manual',
}

/** Pipeline processing status for an ingested event */
export enum PipelineStatus {
  Pending = 'pending',
  Complete = 'complete',
  Partial = 'partial',
}

/** Analytics snapshot intervals */
export enum SnapshotType {
  Daily = 'Daily',
  Weekly = 'Weekly',
  Monthly = 'Monthly',
  Quarterly = 'Quarterly',
}

/** Risk label thresholds: Low [0,0.25), Medium [0.25,0.50), High [0.50,0.75), Critical [0.75,1.0] */
export enum RiskLabel {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical',
}

/** Authentication event types for the audit log */
export enum AuthEventType {
  LoginSuccess = 'login_success',
  LoginFailure = 'login_failure',
  Logout = 'logout',
  TokenRefresh = 'token_refresh',
  TokenRefreshFailure = 'token_refresh_failure',
}
